* [32mDEX-1026-sc6[m
  DEX-290-stop-matcher-on-deserialization-error[m
  DEX-945-utility-methods-tests[m
  DEX-946-order-book-routes[m
  DEX-954-check-ask-and-bids-order[m
  DEX-961-beautify-jenkins[m
  DEX-961-beautify-jenkins-1[m
  DEX-967-matcher-public-key-from-env[m
  DEX-971-order-status-routes-tests[m
  DEX-972-order-routes-tests[m
  DEX-973-order-history-tests[m
  DEX-974-balance-tests[m
  DEX-975-rates-route-tests[m
  DEX-976-snapshot-tests[m
  DEX-979[m
  DEX-979-fix-kafka-tests[m
  DEX-986-fix-delete-orderbook-status-code-on-error[m
  master[m
  new-public-key[m
