flowchart BT
  subgraph Matcher
    MBUc[Blockchain Updates client]
    MEc[Matcher Extension client]
  end
  subgraph Waves Node
    MBUs[Blockchain Updates server]
    MEs[Matcher Extension server]
  end
  MBUs -..->|Blockchain events| MBUc
  MEc ---|Balances request/response| MEs
  MEs -..->|UTX events| MEc
